"use client";
import React, { ReactNode } from "react";
import {
  BottomNavigationAction,
  Box,
  CssBaseline,
  List,
  ListItemButton,
  Avatar,
  ListItemAvatar,
  ListItemText,
  Paper,
  BottomNavigation,
} from "@mui/material";
// import Grid from '@mui/material/Grid2';
import Icon from "../Icon/Icon";

export interface MessageExample {
  primary: string;
  secondary: string;
  person: string;
}

const messageExamples: readonly MessageExample[] = [
  {
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/svg/guest.svg',
  },
  {
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
      person: '/svg/guest.svg',
  },
  {
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/svg/guest.svg',
  },
  {
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/svg/guest.svg',
  },
  {
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/svg/guest.svg',
  },
  {
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
      person: '/svg/guest.svg',
  },
  {
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
      person: '/svg/guest.svg',
  },
];


export default function Appshell({ 
  children = "home",
}: { 
  children?: ReactNode
}) {

  return <>
          <Box sx={{ pb: 7 }}>
            <CssBaseline />
            <List>
              {messageExamples.map(({ primary, secondary, person }, index) => (
                <ListItemButton key={index + person}>
                  <ListItemAvatar>
                    <Avatar alt="Profile Picture" src={person} />
                  </ListItemAvatar>
                  <ListItemText primary={primary} secondary={secondary} />
                </ListItemButton>
              ))}
            </List>
            <Paper sx={{ 
              position: 'fixed', 
              bottom: 0, 
              left: 0, 
              right: 0,
            }} elevation={3}>
            
              <BottomNavigation
                showLabels
                value={0}
                onChange={(event, newValue) => {
                  // setValue(newValue);
                }}>
                <BottomNavigationAction label="Back" 
                  icon={<Icon icon="left" />} />

                <BottomNavigationAction label="New" 
                  icon={<Icon icon="add"/>} />

                <BottomNavigationAction label="Forward" 
                  icon={<Icon icon="right"/>} />

              </BottomNavigation>
            </Paper>
          </Box>
        </>
};
